using System;
using System.Windows;

namespace NBA
{
    /// <summary>
    /// MainWindow.xaml 的交互逻辑
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }
        private void datagrid_AutoGeneratedColumns_1(object sender, EventArgs e)
        {
            datagrid.Columns[0].Visibility = Visibility.Hidden;
            datagrid.Columns[2].Visibility = Visibility.Hidden;
        }

    }
}
